# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Slide

# Model Form Field configuration
form: $/beeasy/slider/models/slide/fields.yaml

# Model Class name
modelClass: BeEasy\Slider\Models\Slide

# Default redirect location
defaultRedirect: beeasy/slider/slides

# Create page
create:
    title: Create Slide
    redirect: beeasy/slider/slides/update/:id
    redirectClose: beeasy/slider/slides

# Update page
update:
    title: Edit Slide
    redirect: beeasy/slider/slides
    redirectClose: beeasy/slider/slides

# Preview page
preview:
    title: Preview Slide
