# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Slide

# Model Form Field configuration
form: $/bedard/slick/models/slide/fields.yaml

# Model Class name
modelClass: Bedard\Slick\Models\Slide

# Default redirect location
defaultRedirect: bedard/slick/slides

# Create page
create:
    title: Create Slide
    redirect: bedard/slick/slides/update/:id
    redirectClose: bedard/slick/slides

# Update page
update:
    title: Edit Slide
    redirect: bedard/slick/slides
    redirectClose: bedard/slick/slides

# Preview page
preview:
    title: Preview Slide